<?php

declare(strict_types=1);

namespace PdxApps\Preflight\Install;

/**
 * How to install and wire up the tool behind one step: the Composer package and the
 * version constraint Preflight recommends, an optional {@see InstallCaveat} for tools that
 * need an explicit decision (e.g. a dev-branch package), and how to seed its config — either
 * a bundled stub file or by delegating to the tool's own init command.
 *
 * These are the constraints Preflight owns on the user's behalf; the install command turns a
 * recipe into the actual `composer require` and config scaffolding.
 */
final readonly class InstallRecipe
{
    /**
     * @param  string  $package  Composer package name, e.g. `phpstan/phpstan`.
     * @param  string  $constraint  Recommended version constraint, e.g. `^2`.
     * @param  InstallCaveat|null  $caveat  An explicit decision the user must make, if any.
     * @param  string|null  $configFile  Config filename to scaffold (content generated by the scaffolder), if any.
     * @param  list<string>|null  $initArgs  Tool args to delegate config creation to (e.g. ['--init']), if any.
     */
    public function __construct(
        public string $package,
        public string $constraint,
        public ?InstallCaveat $caveat = null,
        public ?string $configFile = null,
        public ?array $initArgs = null,
    ) {
    }

    public function requirement(): string
    {
        return $this->package . ':' . $this->constraint;
    }

    public function hasCaveat(): bool
    {
        return $this->caveat instanceof InstallCaveat;
    }
}
